services:
  rabbitmq:
    image: rabbitmq:4.0.7-management
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_ADMIN_PORT:-15672}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
      RABBITMQ_ENABLED_PLUGINS_FILE: /etc/rabbitmq/enabled_plugins
    volumes:
      - ./plugins/rabbitmq_delayed_message_exchange-v4.0.7.ez:/opt/rabbitmq/plugins/rabbitmq_delayed_message_exchange-v4.0.7.ez
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    command: >
      bash -c "
        echo '[rabbitmq_management,rabbitmq_delayed_message_exchange].' > /etc/rabbitmq/enabled_plugins &&
        docker-entrypoint.sh rabbitmq-server
      "

  rabbitmq-setup:
    image: rabbitmq:4.0.7-management
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: "amqp://${RABBITMQ_DEFAULT_USER:-guest}:${RABBITMQ_DEFAULT_PASS:-guest}@rabbitmq:${RABBITMQ_PORT:-5672}"
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
    command: >
      bash -c "
        echo 'Waiting for RabbitMQ to be ready...' &&
        sleep 15 &&
        echo 'Setting up RabbitMQ resources...' &&
        rabbitmqadmin -V / -H rabbitmq -u $RABBITMQ_DEFAULT_USER -p $RABBITMQ_DEFAULT_PASS declare exchange name=delayed_exchange type=x-delayed-message arguments='{"x-delayed-type":"direct"}' &&
        rabbitmqadmin -V / -H rabbitmq -u $RABBITMQ_DEFAULT_USER -p $RABBITMQ_DEFAULT_PASS declare exchange name=dlx_exchange type=direct &&
        rabbitmqadmin -V / -H rabbitmq -u $RABBITMQ_DEFAULT_USER -p $RABBITMQ_DEFAULT_PASS declare queue name=main_queue arguments='{"x-dead-letter-exchange":"dlx_exchange"}' &&
        rabbitmqadmin -V / -H rabbitmq -u $RABBITMQ_DEFAULT_USER -p $RABBITMQ_DEFAULT_PASS declare binding source=delayed_exchange destination=main_queue routing_key=main &&
        rabbitmqadmin -V / -H rabbitmq -u $RABBITMQ_DEFAULT_USER -p $RABBITMQ_DEFAULT_PASS declare queue name=dead_letter_queue &&
        rabbitmqadmin -V / -H rabbitmq -u $RABBITMQ_DEFAULT_USER -p $RABBITMQ_DEFAULT_PASS declare binding source=dlx_exchange destination=dead_letter_queue routing_key=main &&
        echo 'RabbitMQ setup completed successfully!' &&
        echo 'Resources created:' &&
        rabbitmqadmin -V / -H rabbitmq -u $RABBITMQ_DEFAULT_USER -p $RABBITMQ_DEFAULT_PASS list exchanges name type &&
        rabbitmqadmin -V / -H rabbitmq -u $RABBITMQ_DEFAULT_USER -p $RABBITMQ_DEFAULT_PASS list queues name &&
        rabbitmqadmin -V / -H rabbitmq -u $RABBITMQ_DEFAULT_USER -p $RABBITMQ_DEFAULT_PASS list bindings source destination routing_key
      "
    restart: "no"

volumes:
  rabbitmq_data:
