services:
  rabbitmq:
    image: rabbitmq:4.0.7-management
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${DOCKER_RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${DOCKER_RABBITMQ_PASSWORD:-guest}
      RABBITMQ_ENABLED_PLUGINS_FILE: /etc/rabbitmq/enabled_plugins
    volumes:
      - ./plugins/rabbitmq_delayed_message_exchange-v4.0.7.ez:/opt/rabbitmq/plugins/rabbitmq_delayed_message_exchange-v4.0.7.ez
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    command: >
      bash -c "
        echo '[rabbitmq_management,rabbitmq_delayed_message_exchange].' > /etc/rabbitmq/enabled_plugins &&
        docker-entrypoint.sh rabbitmq-server
      "

  rabbitmq-setup:
    image: rabbitmq:4.0.7-management
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: "amqp://${DOCKER_RABBITMQ_USER:-guest}:${DOCKER_RABBITMQ_PASSWORD:-guest}@${DOCKER_RABBITMQ_HOST:-rabbitmq}:${DOCKER_RABBITMQ_PORT:-5672}"
      RABBITMQ_USER: ${DOCKER_RABBITMQ_USER:-guest}
      RABBITMQ_PASS: ${DOCKER_RABBITMQ_PASSWORD:-guest}
      RABBITMQ_HOST: ${DOCKER_RABBITMQ_HOST:-rabbitmq}
    command: >
      bash -c "
        echo 'Waiting for RabbitMQ to be ready...' &&
        sleep 15 &&
        echo 'Setting up RabbitMQ resources...' &&
        rabbitmqadmin -H $${RABBITMQ_HOST} -u $${RABBITMQ_USER} -p $${RABBITMQ_PASS} declare exchange name=delayed_exchange type=x-delayed-message arguments='{\"x-delayed-type\":\"direct\"}' &&
        rabbitmqadmin -H $${RABBITMQ_HOST} -u $${RABBITMQ_USER} -p $${RABBITMQ_PASS} declare exchange name=dlx_exchange type=direct &&
        rabbitmqadmin -H $${RABBITMQ_HOST} -u $${RABBITMQ_USER} -p $${RABBITMQ_PASS} declare queue name=main_queue arguments='{\"x-dead-letter-exchange\":\"dlx_exchange\"}' &&
        rabbitmqadmin -H $${RABBITMQ_HOST} -u $${RABBITMQ_USER} -p $${RABBITMQ_PASS} declare binding source=delayed_exchange destination=main_queue routing_key=main &&
        rabbitmqadmin -H $${RABBITMQ_HOST} -u $${RABBITMQ_USER} -p $${RABBITMQ_PASS} declare queue name=dead_letter_queue &&
        rabbitmqadmin -H $${RABBITMQ_HOST} -u $${RABBITMQ_USER} -p $${RABBITMQ_PASS} declare binding source=dlx_exchange destination=dead_letter_queue routing_key=main &&
        echo 'RabbitMQ setup completed successfully!' &&
        echo 'Resources created:' &&
        rabbitmqadmin -H $${RABBITMQ_HOST} -u $${RABBITMQ_USER} -p $${RABBITMQ_PASS} list exchanges name type &&
        rabbitmqadmin -H $${RABBITMQ_HOST} -u $${RABBITMQ_USER} -p $${RABBITMQ_PASS} list queues name &&
        rabbitmqadmin -H $${RABBITMQ_HOST} -u $${RABBITMQ_USER} -p $${RABBITMQ_PASS} list bindings source destination routing_key
      "
    restart: "no"

volumes:
  rabbitmq_data:
